apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: giftshopui-v6
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: giftshopui
        tier: frontend
        version: v6
    spec:
      containers:
      - name: giftshopui
        image: <YOUR_HARBOR_FQDN>/<YOUR_HARBOR_PROJECT>/<username>-giftshopui:6.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ExternalDependencies_GiftShopAPI_BaseUrl
          valueFrom:
            configMapKeyRef:
              name: giftshopui-config
              key: GiftShopAPIBaseUrl
        # volumeMounts:
        # - name: giftshopui-config
        #   mountPath: /app/GiftShopUI/out/AppConfig.json
        #   subPath: AppConfig.json
      imagePullSecrets:
        - name:  <username>harborsecret
      # volumes:
      # - name: giftshopui-config
      #   configMap:
      #       name: giftshopui-config
---
apiVersion: v1
kind: Service
metadata:
  name: giftshopui
spec:
  #type: LoadBalancer #uncomment this to directly expose with regular Kubernetes without Istio
  selector:
    app: giftshopui
  ports:
  - port: 80
    name: http-giftshopui  # Should start with http- for Istio, Jager and Prometheus to trace requests