apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: giftshopui-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: giftshopui
        tier: frontend
        version: v1
    spec:
      containers:
      - name: giftshopui
        image: <YOUR_HARBOR_FQDN>/<YOUR_HARBOR_PROJECT>/<username>-giftshopui:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name:  <username>harborsecret
---
apiVersion: v1
kind: Service
metadata:
  name: giftshopui
spec:
  #type: LoadBalancer #uncomment this to directly expose with regular Kubernetes without Istio
  selector:
    app: giftshopui
  ports:
  - port: 80
    name: http-giftshopui  # Should start with http- for Istio, Jager and Prometheus to trace requests